### ISSUE TITLE
Does LiFE use t1 input?

### ISSUE THREAD

**Issue by soichih** [brainlife/app-life#2]
app-life currently requires t1 as one of the input file. @kitchell and I believe that it's not used by LiFE, or that it works without it. We ran LiFE with bogus path to t1 and LiFE finished successfully.

@francopestilli Please let me know if we should get rid of t1 input - this simplifies our workflow and make it easier for user to submit LiFE.

**Comment by francopestilli** [comment]
@soichih not necessarily. But it is of help for making plots of the anatomy. If the T1 is not passed the XFORM from the T1 would be necessary. Now we extract that information from the T1 during the ENCODE stage.

**Comment by soichih** [comment]
@francopestilli 

I've looked at the latest encode code, and I couldn't find any code that's using fe.path.anatomy once it's set by feSet - as far as I can tell. There might be some matlab magic happening somewhere, but xform seems to be always set from dwiFile / qto_xyz.

Can you point me to the code where T1 is actually read by encode?

**Comment by francopestilli** [comment]
Let me check when back.

Franco

sent via phone, pardon brevity and mistakes.

On Aug 16, 2017 5:55 PM, "Soichi Hayashi" <notifications@github.com> wrote:

@francopestilli <https://github.com/francopestilli>

I've looked at the latest encode code, and I couldn't find any code that's
using fe.path.anatomy once it's set by feSet - as far as I can tell. There
might be some matlab magic happening somewhere, but xform seems to be
always set from dwiFile / qto_xyz.

Can you point me to the code where T1 is actually read by encode?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brain-life/app-life/issues/2#issuecomment-322817362>,
or mute the thread

**Comment by soichih** [comment]
I've removed the t1 input from app-life for the time being.
